//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyForRent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyForRent()
        {
            this.Viewing = new HashSet<Viewing>();
        }
    
        public string PropertyNo { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string PropertyType { get; set; }
        public short Rooms { get; set; }
        public decimal Rent { get; set; }
        public string OwnerNo { get; set; }
        public string StaffNo { get; set; }
        public string BranchNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viewing> Viewing { get; set; }
    }
}
