//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewing
    {
        public string ClientNo { get; set; }
        public string PropertyNo { get; set; }
        public System.DateTime ViewDate { get; set; }
        public string Comments { get; set; }
    
        public virtual PropertyForRent PropertyForRent { get; set; }
    }
}
